"""seed_factory_queue — generate intent alloys for the BigMama queue.

The published alloys (e.g. qwen3-coder-30b-a3b-compacted-19b-256k) are
huge because they include model-card prose, methodology blockquotes, all
the priorMetricBaselines, etc. That stuff is published-form metadata,
generated by the publish stage AFTER the forge runs.

For queueing the next batch of forges, we want INTENT recipes: minimal,
authored once, dispatchable through alloy_executor + the family-adapter
set + the eval-runner registry. This script is the per-target catalog of
intent recipes — Kash's frontier-target list materialized as files in
.factory/line/intake/.

Each candidate is one Python dict with the four fields the forge needs:
    name              — what continuum-ai/<name> will be on HF
    base_model        — HF id of the source model
    architecture      — source.architecture string (matches FamilyAdapter)
    forge             — the prune target + eval benchmarks for this family

The script renders each candidate to a minimal alloy JSON and copies it
into .factory/line/intake/. From there factory_queue.FactoryWorker
picks them up.

Usage:
    python scripts/seed_factory_queue.py --root .factory --dry-run
    python scripts/seed_factory_queue.py --root .factory   # actually enqueue

The list is the empty-quadrant viral targets Kash mapped:
  Mixtral 8x22B  — single-5090 prosumer headline
  Mixtral 8x7B   — smaller sibling, same layout
  Phi-3.5-MoE    — same layout, 16 experts/layer
  DeepSeek-V2-Lite — routed + shared (shared bit-exact)
  OLMoE-1B-7B    — Qwen3MoE-layout sibling, second §4.1.3.4 anchor
  Qwen3-Coder-30B-A3B — re-publish via the new pipeline (sanity check)
  Qwen3-VL-30B-A3B — VL MoE (vision_safety + MoE pruner together)
  Qwen3-VL-8B     — pure VL forge
  Qwen2.5-Omni-7B — 4-tower omni (vision + audio + talker + token2wav)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from factory_queue import FactoryQueue


# Open LLM Leaderboard v2 — every text-LLM forge runs the full pack so
# every published model has 6-leaderboard coverage.
OPENLLM_V2_BENCHMARKS = ["ifeval", "bbh", "math_hard", "gpqa", "mmlu_pro", "musr"]

# Code-forge benchmarks for coder targets.
CODE_BENCHMARKS = ["humaneval", "humaneval_plus", "livecodebench_v6"]


def _coder_acceptance(*, max_vram_gb: float, anchor_delta_pp: float = -3.0) -> dict:
    """Acceptance criteria for a coder forge.

    Joel's directive: "you are free to publish anything that meets good
    scores, doesn't have to win. just good." So absolute floors are set
    at the LOW end of competitive — the §4.1.3.4 anchorDelta is the real
    gate (no degenerate prune is allowed to ship even if its absolute
    floor passes). The morning's qwen3-coder-30b shipped at Δ −3.7
    against the 92.1 base anchor; -3.0 is the standard ceiling.
    """
    return {
        "benchmarks": {
            "humaneval_plus": {
                "min": 0.45,
                "anchorDelta": anchor_delta_pp,
                "anchorBenchmark": "humaneval_plus",
            },
            "humaneval": {"min": 0.50},
            "livecodebench_v6": {"min": 0.15},
        },
        "hardware": {"maxVramGb": max_vram_gb},
        "integrity": {"modelHashRequired": True, "samplesPathRequired": True},
    }


def _general_acceptance(*, max_vram_gb: float) -> dict:
    """Acceptance criteria for a general-purpose forge — Open LLM Leaderboard v2 floors.

    Floors are at the low end of "competitive on the HF leaderboard."
    A forge that lands here is ship-eligible: not necessarily a
    headline, but credibly good. Better-than-floor is the bonus, not
    the gate.
    """
    return {
        "benchmarks": {
            "ifeval":   {"min": 0.40},
            "bbh":      {"min": 0.35},
            "math_hard":{"min": 0.06},
            "gpqa":     {"min": 0.22},
            "mmlu_pro": {"min": 0.25},
            "musr":     {"min": 0.25},
        },
        "hardware": {"maxVramGb": max_vram_gb},
        "integrity": {"modelHashRequired": True},
    }


def _vl_acceptance(*, max_vram_gb: float) -> dict:
    """Acceptance criteria for a vision-language forge — competitive VL floors."""
    return {
        "benchmarks": {
            "mmmu":    {"min": 0.35},
            "chartqa": {"min": 0.45},
            "docvqa":  {"min": 0.50},
            "ai2d":    {"min": 0.50},
        },
        "hardware": {"maxVramGb": max_vram_gb},
        "integrity": {"modelHashRequired": True},
    }


def _moe_recipe(
    *,
    name: str,
    base_model: str,
    architecture: str,
    layout: str,
    keep_experts: int,
    original_experts: int,
    benchmarks: list[str],
    description: str,
    acceptance: dict | None = None,
    source_geometry: dict | None = None,
) -> dict:
    """Build a minimal MoE expert-prune recipe alloy with an acceptance gate.

    source_geometry is merged into the source block — pass the verified
    HF config values (numLayers, contextLength, totalParamsB, etc.) so
    the intent alloy carries publish-ready geometry from the start.
    """
    prune_pct = round(100 * (1 - keep_experts / original_experts), 1)
    source = {
        "baseModel": base_model,
        "architecture": architecture,
        "isMoE": True,
    }
    if source_geometry:
        source.update(source_geometry)
    alloy = {
        "name": name,
        "version": "0.1.0",
        "description": description,
        "author": "continuum-ai",
        "license": "apache-2.0",
        "source": source,
        "stages": [
            {
                "type": "expert-activation-profile",
                "calibrationCorpus": "heldout_code_python_300ex_125ktok",
                "calibrationCorpusFile": "calibration/heldout_code300.jsonl",
                "metric": "activation_count",
                "metricVersion": "v1.activation_count",
                "implementation": "scripts/expert_activation_profile.py",
            },
            {
                "type": "expert-prune",
                "strategy": "calibration-aware-activation-count",
                "metric": "activation_count",
                "keepExpertsPerLayer": keep_experts,
                "originalExpertsPerLayer": original_experts,
                "prunePct": prune_pct,
                "perLayerNormalized": True,
                "expertTensorLayout": layout,
                "implementation": "scripts/cpu_expert_prune_v2.py",
            },
            {
                "type": "quant",
                "format": "gguf",
                "quantTypes": ["Q4_K_M", "Q5_K_M", "Q8_0"],
                "tool": "llama.cpp llama-quantize",
            },
            {
                "type": "eval",
                "benchmarks": [{"name": b} for b in benchmarks],
                "implementation": "scripts/eval_with_calibration.py",
            },
            {
                "type": "publish",
                "destination": "huggingface",
                "org": "continuum-ai",
                "repoName": name,
            },
        ],
    }
    if acceptance is not None:
        alloy["acceptanceCriteria"] = acceptance
    return alloy


def _dense_recipe(
    *,
    name: str,
    base_model: str,
    architecture: str,
    description: str,
    prune_level: float = 0.30,
    benchmarks: list[str] | None = None,
    acceptance: dict | None = None,
    source_geometry: dict | None = None,
) -> dict:
    """Build a minimal DENSE forge recipe alloy.

    Dense forges go through PruneExecutor → family_adapter.prune() (head
    pruning + training-aware structural compaction), not the MoE expert
    prune path. Stages: prune → train (LoRA recovery) → quant → eval →
    publish. The family adapter (Qwen2DenseAdapter, Qwen3DenseAdapter)
    owns the actual prune algorithm; this recipe just declares intent.
    """
    if benchmarks is None:
        benchmarks = OPENLLM_V2_BENCHMARKS
    source = {
        "baseModel": base_model,
        "architecture": architecture,
        "isMoE": False,
    }
    if source_geometry:
        source.update(source_geometry)
    alloy = {
        "name": name,
        "version": "0.1.0",
        "description": description,
        "author": "continuum-ai",
        "license": "apache-2.0",
        "source": source,
        "stages": [
            {
                "type": "prune",
                "level": prune_level,
                "strategy": "combined",
                "implementation": "scripts/forge_model.py",
            },
            {
                "type": "train",
                "method": "lora",
                "lora_rank": 16,
                "epochs": 1,
                "implementation": "scripts/forge_model.py",
            },
            {
                "type": "quant",
                "format": "gguf",
                "quantTypes": ["Q4_K_M", "Q5_K_M", "Q8_0"],
                "tool": "llama.cpp llama-quantize",
            },
            {
                "type": "eval",
                "benchmarks": [{"name": b} for b in benchmarks],
                "implementation": "scripts/eval_with_calibration.py",
            },
            {
                "type": "publish",
                "destination": "huggingface",
                "org": "continuum-ai",
                "repoName": name,
            },
        ],
    }
    if acceptance is not None:
        alloy["acceptanceCriteria"] = acceptance
    return alloy


def _vl_recipe(
    *,
    name: str,
    base_model: str,
    architecture: str,
    is_moe: bool,
    description: str,
    keep_experts: int | None = None,
    original_experts: int | None = None,
    acceptance: dict | None = None,
    source_geometry: dict | None = None,
) -> dict:
    """Vision-language forge recipe. Routes through QwenVLAdapter which
    handles vision_safety. If is_moe, also runs the MoE expert prune."""
    stages: list[dict] = []
    if is_moe and keep_experts is not None and original_experts is not None:
        stages.extend([
            {
                "type": "expert-activation-profile",
                "calibrationCorpus": "heldout_vqa_400ex",
                "calibrationCorpusFile": "calibration/heldout_vqa400.jsonl",
                "metric": "activation_count",
            },
            {
                "type": "expert-prune",
                "strategy": "calibration-aware-activation-count",
                "metric": "activation_count",
                "keepExpertsPerLayer": keep_experts,
                "originalExpertsPerLayer": original_experts,
                "prunePct": round(100 * (1 - keep_experts / original_experts), 1),
                "expertTensorLayout": "mlp-experts-unfused",
            },
        ])
    stages.extend([
        {
            "type": "modality",
            "preserveTowers": ["vision"],
            "verifyBitExact": True,
        },
        {
            "type": "quant",
            "format": "gguf",
            "quantTypes": ["Q4_K_M", "Q8_0"],
        },
        {
            "type": "eval",
            "benchmarks": [{"name": b} for b in ["mmmu", "chartqa", "docvqa", "ai2d"]],
        },
        {
            "type": "publish",
            "destination": "huggingface",
            "org": "continuum-ai",
            "repoName": name,
        },
    ])
    source = {
        "baseModel": base_model,
        "architecture": architecture,
        "isMoE": is_moe,
    }
    if source_geometry:
        source.update(source_geometry)
    alloy = {
        "name": name,
        "version": "0.1.0",
        "description": description,
        "author": "continuum-ai",
        "license": "apache-2.0",
        "source": source,
        "stages": stages,
    }
    if acceptance is not None:
        alloy["acceptanceCriteria"] = acceptance
    return alloy


# ── The viral-target catalog ────────────────────────────────────────────────


CATALOG: list[dict] = [
    # ── Mixtral family — block_sparse_moe-unfused, the prosumer headline ──
    _moe_recipe(
        name="mixtral-8x22b-instruct-compacted-70b",
        base_model="mistralai/Mixtral-8x22B-Instruct-v0.1",
        architecture="mixtral",
        layout="block_sparse_moe-unfused",
        keep_experts=4,
        original_experts=8,
        source_geometry={
            "totalParamsB": 141.0,
            "activeParamsB": 39.0,
            "numLayers": 56,
            "numExpertsPerLayer": 8,
            "numActivatedExperts": 2,
            "hiddenSize": 6144,
            "intermediateSize": 16384,
            "contextLength": 65536,
            "license": "apache-2.0",
        },
        benchmarks=CODE_BENCHMARKS + OPENLLM_V2_BENCHMARKS,
        acceptance=_coder_acceptance(max_vram_gb=24.0, anchor_delta_pp=-3.0),
        description=(
            "Single-5090 prosumer headline: Mixtral 8x22B compacted from "
            "141B/39B-active to ~70B/39B-active by pruning 8→4 experts per "
            "layer via calibration-aware activation count. ~22GB Q4_K_M. "
            "Empty quadrant on HF — nothing in this VRAM tier today."
        ),
    ),
    _moe_recipe(
        name="mixtral-8x7b-instruct-compacted-24b",
        base_model="mistralai/Mixtral-8x7B-Instruct-v0.1",
        architecture="mixtral",
        layout="block_sparse_moe-unfused",
        keep_experts=4,
        original_experts=8,
        source_geometry={
            "totalParamsB": 46.7,
            "activeParamsB": 12.9,
            "numLayers": 32,
            "numExpertsPerLayer": 8,
            "numActivatedExperts": 2,
            "hiddenSize": 4096,
            "intermediateSize": 14336,
            "contextLength": 32768,
            "license": "apache-2.0",
        },
        benchmarks=CODE_BENCHMARKS + OPENLLM_V2_BENCHMARKS,
        acceptance=_coder_acceptance(max_vram_gb=16.0, anchor_delta_pp=-3.0),
        description=(
            "Mixtral 8x7B compacted from 47B/13B-active to ~24B/13B-active "
            "via 8→4 expert pruning. Smaller sibling of the 8x22B headline; "
            "same block_sparse_moe-unfused layout, identical algorithm via "
            "the family-adapter inheritance chain."
        ),
    ),
    # ── Phi-3.5-MoE — same layout, different geometry (16 experts) ──
    _moe_recipe(
        name="phi-3-5-moe-instruct-compacted-22b",
        base_model="microsoft/Phi-3.5-MoE-instruct",
        architecture="phimoe",
        layout="block_sparse_moe-unfused",
        keep_experts=8,
        original_experts=16,
        source_geometry={
            "totalParamsB": 41.9,
            "activeParamsB": 6.6,
            "numLayers": 32,
            "numExpertsPerLayer": 16,
            "numActivatedExperts": 2,
            "hiddenSize": 4096,
            "intermediateSize": 6400,
            "contextLength": 131072,
            "license": "mit",
        },
        benchmarks=OPENLLM_V2_BENCHMARKS,
        acceptance=_general_acceptance(max_vram_gb=14.0),
        description=(
            "Phi-3.5-MoE compacted from 41.9B/6.6B-active to ~22B/6.6B-active "
            "via 16→8 expert pruning. Inherits the entire pruning algorithm "
            "from MixtralAdapter via PhiMoEAdapter — same layout, different "
            "geometry, zero duplicated body."
        ),
    ),
    # ── DeepSeek-V2-Lite — routed + shared, shared bit-exact ──
    _moe_recipe(
        name="deepseek-v2-lite-chat-compacted",
        base_model="deepseek-ai/DeepSeek-V2-Lite-Chat",
        architecture="deepseek_v2",
        layout="deepseek-routed-shared",
        keep_experts=32,
        original_experts=64,
        source_geometry={
            "totalParamsB": 15.7,
            "activeParamsB": 2.4,
            "numLayers": 27,
            "numExpertsPerLayer": 64,
            "numSharedExperts": 2,
            "numActivatedExperts": 6,
            "firstKDenseReplace": 1,
            "hiddenSize": 2048,
            "moeIntermediateSize": 1408,
            "contextLength": 163840,
            "license": "deepseek",
        },
        benchmarks=CODE_BENCHMARKS + OPENLLM_V2_BENCHMARKS,
        acceptance=_coder_acceptance(max_vram_gb=10.0, anchor_delta_pp=-3.0),
        description=(
            "DeepSeek-V2-Lite compacted via DEEPSEEK_V2_LAYOUT — 64→32 routed "
            "experts per layer with the shared expert pathway preserved "
            "bit-exact (verified in synthetic E2E test). The shared expert "
            "carries the always-fires capability the model relies on."
        ),
    ),
    # ── OLMoE — second §4.1.3.4 anchor, qwen3_moe layout sibling ──
    _moe_recipe(
        name="olmoe-1b-7b-0924-instruct-compacted",
        base_model="allenai/OLMoE-1B-7B-0924-Instruct",
        architecture="olmoe",
        layout="mlp-experts-unfused",
        keep_experts=32,
        original_experts=64,
        source_geometry={
            "totalParamsB": 6.9,
            "activeParamsB": 1.3,
            "numLayers": 16,
            "numExpertsPerLayer": 64,
            "numActivatedExperts": 8,
            "hiddenSize": 2048,
            "intermediateSize": 1024,
            "contextLength": 4096,
            "license": "apache-2.0",
        },
        benchmarks=OPENLLM_V2_BENCHMARKS,
        acceptance=_general_acceptance(max_vram_gb=6.0),
        description=(
            "OLMoE-1B-7B compacted via the MoEUnfusedExpertsBase shared base "
            "(same code path as Qwen3MoE, different family discriminator). "
            "Second §4.1.3.4 cross-architecture anchor."
        ),
    ),
    # ── Qwen3-Coder-30B-A3B — re-publish via the new pipeline ──
    _moe_recipe(
        name="qwen3-coder-30b-a3b-compacted-19b-256k-v2",
        base_model="Qwen/Qwen3-Coder-30B-A3B-Instruct",
        architecture="qwen3_moe",
        layout="mlp-experts-unfused",
        keep_experts=80,
        original_experts=128,
        source_geometry={
            "totalParamsB": 30.5,
            "activeParamsB": 3.3,
            "numLayers": 48,
            "numExpertsPerLayer": 128,
            "numActivatedExperts": 8,
            "hiddenSize": 2048,
            "moeIntermediateSize": 768,
            "contextLength": 262144,
            "license": "apache-2.0",
        },
        benchmarks=CODE_BENCHMARKS + OPENLLM_V2_BENCHMARKS,
        acceptance=_coder_acceptance(max_vram_gb=12.0, anchor_delta_pp=-3.7),
        description=(
            "Re-forge of the morning's flagship via the new factory pipeline "
            "as a sanity check. Same recipe, same target, but routed through "
            "FactoryWorker → alloy_executor → eval registry → publish. The "
            "v2 numbers should match v1 within bench noise; if they don't, "
            "the bug-first frame fires (algorithmic failure first, model "
            "second — the §4.1.3.4 lesson)."
        ),
    ),
    # ── Vision: Qwen3-VL dense (8B) and Qwen3-VL MoE (30B-A3B) ──
    # Verified from HF config.json:
    #   Qwen3-VL-8B-Instruct        model_type: qwen3_vl
    #     text_config: 36 layers, hidden=4096, intermediate=12288, 262K ctx
    #   Qwen3-VL-30B-A3B-Instruct   model_type: qwen3_vl_moe
    #     text_config: 48 layers, 128 experts (8 active), moe_inter=768, 262K ctx
    _vl_recipe(
        name="qwen3-vl-8b-instruct-compacted",
        base_model="Qwen/Qwen3-VL-8B-Instruct",
        architecture="qwen3_vl",
        is_moe=False,
        source_geometry={
            "totalParamsB": 8.0,
            "numLayers": 36,
            "hiddenSize": 4096,
            "intermediateSize": 12288,
            "contextLength": 262144,
            "license": "apache-2.0",
        },
        acceptance=_vl_acceptance(max_vram_gb=10.0),
        description=(
            "Qwen3-VL-8B (dense, 36 layers, 4096 hidden, 262K context) "
            "forged with vision-tower bit-exact preservation via "
            "QwenVLAdapter. The vision encoder is whitelisted; only the LLM "
            "side is touched. Vision benchmarks: MMMU, ChartQA, DocVQA, AI2D."
        ),
    ),
    _vl_recipe(
        name="qwen3-vl-30b-a3b-instruct-compacted-19b-262k",
        base_model="Qwen/Qwen3-VL-30B-A3B-Instruct",
        architecture="qwen3_vl_moe",
        is_moe=True,
        keep_experts=80,
        original_experts=128,
        source_geometry={
            "totalParamsB": 30.5,
            "activeParamsB": 3.3,
            "numLayers": 48,
            "numExpertsPerLayer": 128,
            "numActivatedExperts": 8,
            "hiddenSize": 2048,
            "moeIntermediateSize": 768,
            "contextLength": 262144,
            "license": "apache-2.0",
        },
        acceptance=_vl_acceptance(max_vram_gb=14.0),
        description=(
            "Qwen3-VL-30B-A3B (text_config: 48 layers × 128 experts × 8 "
            "active, 262K context) — the most architecturally interesting "
            "target in the catalog: vision tower + Qwen3MoE LLM in one "
            "model. Routes through QwenVLAdapter (vision_safety) AND the "
            "MoE expert pruner via the same QWEN3_MOE_LAYOUT the morning's "
            "qwen3-coder-30b flagship was forged through. Vision tower "
            "preserved bit-exact, 128→80 LLM experts via calibration-aware "
            "activation count. Same prune ratio as the morning's flagship "
            "to preserve the §4.1.3.4 anchor delta."
        ),
    ),
    # ── Qwen3-30B-A3B (general, NOT coder) — sibling of the morning's flagship ──
    _moe_recipe(
        name="qwen3-30b-a3b-compacted-19b-262k",
        base_model="Qwen/Qwen3-30B-A3B",
        architecture="qwen3_moe",
        layout="mlp-experts-unfused",
        keep_experts=80,
        original_experts=128,
        source_geometry={
            "totalParamsB": 30.5,
            "activeParamsB": 3.3,
            "numLayers": 48,
            "numExpertsPerLayer": 128,
            "numActivatedExperts": 8,
            "hiddenSize": 2048,
            "moeIntermediateSize": 768,
            "contextLength": 262144,
            "license": "apache-2.0",
        },
        benchmarks=OPENLLM_V2_BENCHMARKS,
        acceptance=_general_acceptance(max_vram_gb=12.0),
        description=(
            "Qwen3-30B-A3B (general) compacted from 30.5B/3.3B-active to "
            "~19B/3.3B-active by pruning 128→80 experts per layer via "
            "calibration-aware activation count. Same recipe as the morning's "
            "qwen3-coder-30b flagship but pointed at the GENERAL Open LLM "
            "Leaderboard v2 pack instead of the code pack. Sibling forge: "
            "tests whether the §4.1.3.4 methodology generalizes from "
            "code-domain calibration to general-purpose calibration."
        ),
    ),
    # ── Qwen2.5-VL-7B-Instruct — small VL forge for the 12GB tier ──
    _vl_recipe(
        name="qwen2-5-vl-7b-instruct-compacted",
        base_model="Qwen/Qwen2.5-VL-7B-Instruct",
        architecture="qwen2_5_vl",
        is_moe=False,
        source_geometry={
            "totalParamsB": 8.3,
            "numLayers": 28,
            "hiddenSize": 3584,
            "intermediateSize": 18944,
            "contextLength": 32768,
            "license": "apache-2.0",
        },
        acceptance=_vl_acceptance(max_vram_gb=8.0),
        description=(
            "Qwen2.5-VL-7B (28 layers, 3584 hidden) — small VL forge for "
            "the 12GB consumer GPU tier. Vision tower preserved bit-exact "
            "via QwenVLAdapter; LLM side compacted via dense head pruning."
        ),
    ),
    # ── Qwen2.5-VL-32B-Instruct — bigger VL forge for the 24GB tier ──
    _vl_recipe(
        name="qwen2-5-vl-32b-instruct-compacted",
        base_model="Qwen/Qwen2.5-VL-32B-Instruct",
        architecture="qwen2_5_vl",
        is_moe=False,
        source_geometry={
            "totalParamsB": 33.5,
            "numLayers": 64,
            "hiddenSize": 5120,
            "intermediateSize": 27648,
            "contextLength": 32768,
            "license": "apache-2.0",
        },
        acceptance=_vl_acceptance(max_vram_gb=20.0),
        description=(
            "Qwen2.5-VL-32B (64 layers, 5120 hidden) — bigger VL forge "
            "for the 24GB single-5090 tier. Vision tower preserved "
            "bit-exact, dense head pruning on the LLM. Empty quadrant: no "
            "32B-class VL model on HF fits 24GB at Q4 today."
        ),
    ),
    # ── Dense Qwen2.5 forges — variety beyond the MoE empty quadrant ──
    # Verified from HF config.json:
    #   Qwen/Qwen2.5-7B-Instruct           model_type: qwen2, 28L × 3584
    #   Qwen/Qwen2.5-14B-Instruct          model_type: qwen2, 48L × 5120
    #   Qwen/Qwen2.5-Coder-32B-Instruct    model_type: qwen2, 64L × 5120
    # Dispatch through Qwen2DenseAdapter via PruneExecutor → prune().
    _dense_recipe(
        name="qwen2-5-7b-instruct-compacted",
        base_model="Qwen/Qwen2.5-7B-Instruct",
        architecture="qwen2",
        prune_level=0.25,
        source_geometry={
            "totalParamsB": 7.6,
            "numLayers": 28,
            "hiddenSize": 3584,
            "intermediateSize": 18944,
            "contextLength": 32768,
            "license": "apache-2.0",
        },
        acceptance=_general_acceptance(max_vram_gb=8.0),
        description=(
            "Qwen2.5-7B-Instruct compacted via dense head pruning (25% "
            "removed) + LoRA recovery. Routes through Qwen2DenseAdapter. "
            "The dense companion to the MoE catalog — proves the same "
            "factory loop handles both architectures end to end."
        ),
    ),
    _dense_recipe(
        name="qwen2-5-14b-instruct-compacted",
        base_model="Qwen/Qwen2.5-14B-Instruct",
        architecture="qwen2",
        prune_level=0.30,
        source_geometry={
            "totalParamsB": 14.7,
            "numLayers": 48,
            "hiddenSize": 5120,
            "intermediateSize": 13824,
            "contextLength": 32768,
            "license": "apache-2.0",
        },
        acceptance=_general_acceptance(max_vram_gb=12.0),
        description=(
            "Qwen2.5-14B-Instruct compacted via dense head pruning (30% "
            "removed) + LoRA recovery. Lands in the 12GB VRAM tier "
            "(above 7B Q4, below the 32B class) — a small empty "
            "quadrant on HF for the dense Qwen2.5 family."
        ),
    ),
    _dense_recipe(
        name="qwen2-5-coder-32b-instruct-compacted",
        base_model="Qwen/Qwen2.5-Coder-32B-Instruct",
        architecture="qwen2",
        prune_level=0.30,
        benchmarks=CODE_BENCHMARKS + OPENLLM_V2_BENCHMARKS,
        source_geometry={
            "totalParamsB": 32.5,
            "numLayers": 64,
            "hiddenSize": 5120,
            "intermediateSize": 27648,
            "contextLength": 131072,
            "license": "apache-2.0",
        },
        acceptance=_coder_acceptance(max_vram_gb=20.0, anchor_delta_pp=-3.0),
        description=(
            "Qwen2.5-Coder-32B-Instruct compacted via dense head pruning "
            "(30% removed) + LoRA recovery on a code corpus. The dense "
            "coder counterpart to the MoE qwen3-coder-30b-a3b flagship; "
            "tests whether the §4.1.3.4 calibration-aware methodology "
            "generalizes from MoE expert ranking to dense head ranking."
        ),
    ),
    # ── GraniteMoE — fused-tensor pruning (structurally distinct) ──
    # Verified from HF config.json:
    #   ibm-granite/granite-3.0-3b-a800m-instruct
    #   model_type: granitemoe, 32L × 40 experts × 8 active per token
    #   hidden 1536, intermediate 512, ctx 4096
    # The fused-tensor layout means all experts share input_linear /
    # output_linear / router tensors along an expert axis. Pruning
    # SLICES along axis=0 instead of dropping/renaming named entries.
    _moe_recipe(
        name="granite-3-0-3b-a800m-compacted",
        base_model="ibm-granite/granite-3.0-3b-a800m-instruct",
        architecture="granitemoe",
        layout="granite-moe-fused",
        keep_experts=20,
        original_experts=40,
        source_geometry={
            "totalParamsB": 3.4,
            "activeParamsB": 0.8,
            "numLayers": 32,
            "numExpertsPerLayer": 40,
            "numActivatedExperts": 8,
            "hiddenSize": 1536,
            "intermediateSize": 512,
            "contextLength": 4096,
            "license": "apache-2.0",
        },
        benchmarks=OPENLLM_V2_BENCHMARKS,
        acceptance=_general_acceptance(max_vram_gb=4.0),
        description=(
            "IBM Granite-3.0-3B-A800M compacted from 3.4B/0.8B-active to "
            "~1.7B/0.8B-active by pruning 40→20 experts per layer via "
            "calibration-aware activation count. THE ONLY entry in the "
            "catalog that uses the fused-tensor layout (granite-moe-fused) "
            "— Granite stores all experts in one big tensor per layer along "
            "an expert axis, so pruning SLICES the tensor instead of "
            "dropping/renaming named entries. First proof point for the "
            "structurally-distinct pruner path."
        ),
    ),
    # ── Omni: Qwen2.5-Omni — 4-tower whitelist ──
    _vl_recipe(
        name="qwen2-5-omni-7b-compacted",
        base_model="Qwen/Qwen2.5-Omni-7B",
        architecture="qwen2_5_omni",
        is_moe=False,
        source_geometry={
            "totalParamsB": 7.0,
            "numTalkerLayers": 24,
            "talkerHiddenSize": 896,
            "modalities": ["text", "vision", "audio", "speech"],
            "license": "apache-2.0",
        },
        acceptance=_vl_acceptance(max_vram_gb=10.0),
        description=(
            "Qwen2.5-Omni-7B forged with all 4 encoder/decoder towers "
            "preserved (vision + audio + talker + token2wav) via "
            "QwenOmniAdapter. The omni_safety whitelist covers thinker.visual, "
            "thinker.audio, talker, and token2wav."
        ),
    ),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".factory", help="queue root directory")
    ap.add_argument("--dry-run", action="store_true", help="print, do not enqueue")
    args = ap.parse_args()

    root = Path(args.root)
    if not args.dry_run:
        queue = FactoryQueue(root)

    print(f"factory queue catalog: {len(CATALOG)} candidates")
    for i, alloy in enumerate(CATALOG, start=1):
        name = alloy["name"]
        base = alloy["source"]["baseModel"]
        arch = alloy["source"]["architecture"]
        is_moe = alloy["source"].get("isMoE", False)
        flag = "MoE" if is_moe else "dense"
        print(f"  {i}. {name}")
        print(f"     ← {base}  ({arch}, {flag})")

        if args.dry_run:
            continue

        # Write to a temp path then enqueue.
        tmp = root / f"_seed_{name}.alloy.json"
        tmp.parent.mkdir(parents=True, exist_ok=True)
        tmp.write_text(json.dumps(alloy, indent=2))
        try:
            enqueued = queue.enqueue(tmp)
            print(f"     → enqueued at {enqueued.relative_to(root)}")
        finally:
            tmp.unlink(missing_ok=True)

    if not args.dry_run:
        print(f"\nfinal stats: {queue.stats()}")
        print(f"start the worker: python -m factory_queue --root {args.root} --max-iters {len(CATALOG)}")


if __name__ == "__main__":
    main()
